[package]
name = "sleep-file-parser"
version = "0.0.1"
license = "Apache-2.0"
repository = "https://github.com/datrs/sleep-file-parser"
documentation = "https://docs.rs/sleep-file-parser"
description = "Parse Dat protocol SLEEP files"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]

[dependencies]
nom = "3.2.1"
